
//
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
//

using System.Reflection;

[assembly: AssemblyTitle("AdvancedFlyByWireNeo")]
[assembly: KSPModFolder("AdvancedFlyByWireNeo")]
[assembly: AssemblyProduct("AdvancedFlyByWireNeo")]

[assembly: AssemblyVersion("2.1.8.3")]
[assembly: AssemblyFileVersion("2.1.8.3")]
